// Code generated by golazy. DO NOT EDIT.
package handler

import (
	"github.com/gin-gonic/gin"
	v1 "test/internal/handler/v1"

	v1user "test/internal/handler/v1/user"

	v1ws "test/internal/handler/v1/ws"

	"test/internal/svc"
)

func RegisterHandlers(server *gin.Engine, serverCtx *svc.ServiceContext) {
	gv1 := server.Group("/v1")
	{
		gv1.POST("/sign_in", v1.UserSignInHandler(serverCtx))
		gv1.POST("/sign_up", v1.UserSignUpHandler(serverCtx))
		gv1.POST("/sign_out", v1.UserSignOutHandler(serverCtx))
	}

	gv1user := server.Group("/v1/user")
	{
		gv1user.GET("/list", v1user.GetUserListHandler(serverCtx))
		gv1user.PUT("/add", v1user.AddUserHandler(serverCtx))
		gv1user.POST("/edit", v1user.EditUserHandler(serverCtx))
		gv1user.DELETE("/delete", v1user.DeleteUserHandler(serverCtx))
		gv1user.GET("/:id", v1user.GetUserByIdHandler(serverCtx))
	}

	gv1ws := server.Group("/v1/ws")
	{
		gv1ws.GET("/market", v1ws.WsMarketListHandler(serverCtx))
	}
}
